# Generated by Django 5.1.3 on 2024-11-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(unique=True)),
                ('image', models.ImageField(upload_to='baby_images/')),
                ('average_weight', models.DecimalField(decimal_places=2, help_text='Weight in grams', max_digits=5)),
                ('average_size', models.DecimalField(decimal_places=2, help_text='Size in centimeters', max_digits=5)),
            ],
        ),
    ]
