# Generated by Django 5.1.3 on 2024-11-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_babyweek_average_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyweek',
            name='average_weight',
            field=models.DecimalField(decimal_places=4, help_text='Weight in kilograms', max_digits=8),
        ),
    ]
