# Generated by Django 5.1.3 on 2024-11-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_babyweek_average_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_sex', models.CharField(max_length=20)),
                ('due_date_choice', models.CharField(max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('first_child', models.CharField(max_length=3)),
                ('age_group', models.CharField(max_length=20)),
            ],
        ),
    ]
