# Generated by Django 5.1.3 on 2024-11-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pregnancydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancydetails',
            name='nin_number',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
