# Generated by Django 5.1.3 on 2024-11-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_pregnancydetails_nin_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregnancydetails',
            old_name='nin_number',
            new_name='nin',
        ),
    ]
