# Generated by Django 5.1.3 on 2024-11-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_pregnancydetails_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancydetails',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
