# Generated by Django 5.1.3 on 2024-11-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_insightcategory_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='insights_images/'),
        ),
    ]
